# **env**
@hostname = http://localhost:5000
@api-endpoints = http://localhost:5000/api/v1

# **index endpoint**

# Homepage
GET {{hostname}}

###

# Dashboard
GET {{hostname}}/dashboard

###

# **Auth Endpoint**

# signup
POST {{hostname}}/signup
Content-Type: application/json

{
  "username": "honeygirl",
  "email": "honeygirl2@gmail.com",
  "password": "asirii",
  "repeatPassword": "asirii"
}

###
# Login
POST {{hostname}}/login

###

# logout
POST {{hostname}}/logout
